import React from "react";

const useProfileInputs = (
  checkBook1,
  checkBook2,
  checkBook3,
  checkCancel1,
  checkCancel2,
  checkCancel3,
  checkEmails1,
  checkEmails2,
  checkEmails3,
  checkGallery1,
  checkGallery2,
  checkGallery3,
  checkOpinions1,
  checkOpinions2,
  checkOpinions3,
  checkOpenShop1,
  checkOpenShop2,
  checkOpenShop3,
  checkServices1,
  checkServices2,
  checkServices3,
  checkPermissions1,
  checkPermissions2,
  checkPermissions3,
  setCheckBook1,
  setCheckBook2,
  setCheckBook3,
  setCheckCancel1,
  setCheckCancel2,
  setCheckCancel3,
  setCheckEmail1,
  setCheckEmail2,
  setCheckEmail3,
  setCheckGallery1,
  setCheckGallery2,
  setCheckGallery3,
  setCheckOpinions1,
  setCheckOpinions2,
  setCheckOpinions3,
  setCheckOpenShop1,
  setCheckOpenShop2,
  setCheckOpenShop3,
  setCheckServices1,
  setCheckServices2,
  setCheckServices3,
  setCheckPermissions1,
  setCheckPermissions2,
  setCheckPermissions3
) => {
  let inputsPermissions = [
    {
      labelName: "Enable book",
      id1: "enableBook1",
      id2: "enableBook2",
      id3: "enableBook3",
      enable1: checkBook1,
      enable2: checkBook2,
      enable3: checkBook3,
      callback1: () => setCheckBook1((prevValue) => !prevValue),
      callback2: () => setCheckBook2((prevValue) => !prevValue),
      callback3: () => setCheckBook3((prevValue) => !prevValue),
    },
    {
      labelName: "Enable cancel",
      id1: "enableCancel1",
      id2: "enableCancel2",
      id3: "enableCancel3",
      enable1: checkCancel1,
      enable2: checkCancel2,
      enable3: checkCancel3,
      callback1: () => setCheckCancel1((prevValue) => !prevValue),
      callback2: () => setCheckCancel2((prevValue) => !prevValue),
      callback3: () => setCheckCancel3((prevValue) => !prevValue),
    },
    {
      labelName: "Enable delete email",
      id1: "enableEmail1",
      id2: "enableEmail2",
      id3: "enableEmail3",
      enable1: checkEmails1,
      enable2: checkEmails2,
      enable3: checkEmails3,
      callback1: () => setCheckEmail1((prevValue) => !prevValue),
      callback2: () => setCheckEmail2((prevValue) => !prevValue),
      callback3: () => setCheckEmail3((prevValue) => !prevValue),
    },
    {
      labelName: "Enable add/delete/edit image",
      id1: "enableImage1",
      id2: "enableImage2",
      id3: "enableImage3",
      enable1: checkGallery1,
      enable2: checkGallery2,
      enable3: checkGallery3,
      callback1: () => setCheckGallery1((prevValue) => !prevValue),
      callback2: () => setCheckGallery2((prevValue) => !prevValue),
      callback3: () => setCheckGallery3((prevValue) => !prevValue),
    },

    {
      labelName: "Enable delete opinion",
      id1: "enableOpinion1",
      id2: "enableOpinion2",
      id3: "enableOpinion3",
      enable1: checkOpinions1,
      enable2: checkOpinions2,
      enable3: checkOpinions3,
      callback1: () => setCheckOpinions1((prevValue) => !prevValue),
      callback2: () => setCheckOpinions2((prevValue) => !prevValue),
      callback3: () => setCheckOpinions3((prevValue) => !prevValue),
    },
    {
      labelName: "Enable add/delete/edit open hours",
      id1: "enableOpenHours1",
      id2: "enableOpenHours2",
      id3: "enableOpenHours3",
      enable1: checkOpenShop1,
      enable2: checkOpenShop2,
      enable3: checkOpenShop3,
      callback1: () => setCheckOpenShop1((prevValue) => !prevValue),
      callback2: () => setCheckOpenShop2((prevValue) => !prevValue),
      callback3: () => setCheckOpenShop3((prevValue) => !prevValue),
    },
    {
      labelName: "Enable add/delete/edit services",
      id1: "enableServices1",
      id2: "enableServices2",
      id3: "enableServices3",
      enable1: checkServices1,
      enable2: checkServices2,
      enable3: checkServices3,
      callback1: () => setCheckServices1((prevValue) => !prevValue),
      callback2: () => setCheckServices2((prevValue) => !prevValue),
      callback3: () => setCheckServices3((prevValue) => !prevValue),
    },
    {
      labelName: "Enable permissions",
      id1: "enablePermissions1",
      id2: "enablePermissions2",
      id3: "enablePermissions3",
      enable1: checkPermissions1,
      enable2: checkPermissions2,
      enable3: checkPermissions3,
      callback1: () => setCheckPermissions1((prevValue) => !prevValue),
      callback2: () => setCheckPermissions2((prevValue) => !prevValue),
      callback3: () => setCheckPermissions3((prevValue) => !prevValue),
    },
  ];

  return { inputsPermissions };
};

export default useProfileInputs;
