export const menuOptions = [
  {
    classFontAwesome: "fas fa-th-large",
    classIcon: "admin__icon",
    classItem: "admin__item",
    classLink: "admin__link",
    classOption: "admin__option",
    activeClassLink: "admin__link--active",
    text: "Dashboard",
    pathLink: "/admin",
  },
  {
    classFontAwesome: "far fa-calendar-check",
    classIcon: "admin__icon",
    classItem: "admin__item",
    classLink: "admin__link",
    classOption: "admin__option",
    activeClassLink: "admin__link--active",
    text: "Booked",
    pathLink: "/admin/booked",
  },
  {
    classFontAwesome: "far fa-calendar-times",
    classIcon: "admin__icon",
    classItem: "admin__item",
    classLink: "admin__link",
    classOption: "admin__option",
    activeClassLink: "admin__link--active",
    text: "Canceled",
    pathLink: "/admin/canceled",
  },
  {
    classFontAwesome: "fas fa-at",
    classIcon: "admin__icon",
    classItem: "admin__item",
    classLink: "admin__link",
    classOption: "admin__option",
    activeClassLink: "admin__link--active",
    text: "Emails",
    pathLink: "/admin/emails",
  },
  {
    classFontAwesome: "far fa-image",
    classIcon: "admin__icon",
    classItem: "admin__item",
    classLink: "admin__link",
    classOption: "admin__option",
    activeClassLink: "admin__link--active",
    text: "Gallery",
    pathLink: "/admin/gallery",
  },
  {
    classFontAwesome: "far fa-calendar",
    classIcon: "admin__icon",
    classItem: "admin__item",
    classLink: "admin__link",
    classOption: "admin__option",
    activeClassLink: "admin__link--active",
    text: "Appointments",
    pathLink: "/admin/apponitments",
  },
  {
    classFontAwesome: "far fa-clock",
    classIcon: "admin__icon",
    classItem: "admin__item",
    classLink: "admin__link",
    classOption: "admin__option",
    activeClassLink: "admin__link--active",
    text: "Shop",
    pathLink: "/admin/shop",
  },
  {
    classFontAwesome: "far fa-comments",
    classIcon: "admin__icon",
    classItem: "admin__item",
    classLink: "admin__link",
    classOption: "admin__option",
    activeClassLink: "admin__link--active",
    text: "Opinions",
    pathLink: "/admin/opinions",
  },
  {
    classFontAwesome: "far fa-user-circle",
    classIcon: "admin__icon",
    classItem: "admin__item",
    classLink: "admin__link",
    classOption: "admin__option",
    activeClassLink: "admin__link--active",
    text: "Profile",
    pathLink: "/admin/profile",
  },
  {
    classFontAwesome: "fas fa-tag",
    classIcon: "admin__icon",
    classItem: "admin__item",
    classLink: "admin__link",
    classOption: "admin__option",
    activeClassLink: "admin__link--active",
    text: "Service",
    pathLink: "/admin/service",
  },
];
